In [1]:
import numpy as np


In [2]:
np1=np.array([1,2,3])


In [3]:
np1

array([1, 2, 3])

In [4]:
type(np1)

numpy.ndarray

In [7]:
Mat1=np.array([[2,3],[4,5]])

In [8]:
Mat1


array([[2, 3],
       [4, 5]])

In [10]:
np1.shape

(3,)

In [11]:
Mat1.shape

(2, 2)

In [12]:
np1.dtype

dtype('int32')

In [13]:
Mat1.dtype

dtype('int32')

In [14]:
Mat1[0,0]=5

In [15]:
Mat1

array([[5, 3],
       [4, 5]])

In [21]:
Mat2= np.arange(0,10,5)

In [22]:
Mat2

array([0, 5])

In [24]:
Mat3=np.linspace(0,10,20)

In [25]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
Mat4=np.random.rand(5,5)

In [27]:
Mat4

array([[0.69876353, 0.64213993, 0.27487432, 0.12761659, 0.22701898],
       [0.20901105, 0.96144596, 0.80090935, 0.94621106, 0.34887486],
       [0.58426701, 0.37525528, 0.42897774, 0.41737422, 0.98871364],
       [0.44893166, 0.49819452, 0.1014994 , 0.4615329 , 0.69043279],
       [0.10060009, 0.00974606, 0.60618569, 0.79170803, 0.80725495]])

In [30]:
Mat5=np.random.randn(5,5)

In [31]:
Mat5

array([[ 0.04885257,  0.69785082,  0.24095683, -0.05134741,  1.55543141],
       [ 1.55176248, -1.78892792,  0.42048892,  0.44826588,  1.16766775],
       [ 1.23436164, -1.06506377,  0.66254046, -1.93494701, -0.85078819],
       [-0.74744224,  0.24184233,  1.06926523,  1.04640595,  0.20362762],
       [ 0.89612182, -1.09948553,  0.23540858,  1.41923794,  0.34916577]])

In [32]:
Mat5[0,0]

0.04885257354447779

In [33]:
Mat5[0,1]

0.6978508202845265

In [35]:
Mat5[0:3:]

array([[ 0.04885257,  0.69785082,  0.24095683, -0.05134741,  1.55543141]])

In [1]:
import pandas as pd

In [8]:
data1 = pd.read_csv('C:/Users/SHAMBASHIB MAJUMDAR/Desktop/original(1).csv', header = 0)

FileNotFoundError: [Errno 2] File C:/Users/SHAMBASHIB MAJUMDAR/Desktop/original(1).csv does not exist: 'C:/Users/SHAMBASHIB MAJUMDAR/Desktop/original(1).csv'

## Seaborn library

In [9]:
import seaborn as sns
